version: '2'
services:
  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
      - ./build:/var/build
    depends_on:
      - sn_hub
    environment:
      HUB_HOST: sn_hub
      NODE_MAX_SESSION: 1
      GRID_CLEAN_UP_CYCLE: 60000
      NODE_MAX_INSTANCES: 1

  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
      - ./build:/var/build
    depends_on:
      - sn_hub
    environment:
      HUB_HOST: sn_hub
      NODE_MAX_SESSION: 1
      GRID_CLEAN_UP_CYCLE: 60000
      NODE_MAX_INSTANCES: 1

  sn_hub:
    image: selenium/hub
    environment:
      GRID_BROWSER_TIMEOUT: 40
    ports:
      - "4444:4444"

